/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "airport.h"

findairport_ret *
findairport_1_svc(airportlocation *argp, struct svc_req *rqstp)
{
	printf("AIRPORT...\n");

	static findairport_ret result;
	airportlocation args = *argp;
	airportlist newlist;
	airportlist *listptr;
	char cityname [] = "Seattle";
	char statename [] = "WA";
	char code [] = "POO";
	int distance = 10;
	float lat = args.latitude;
	float longi = args.longitude;
	xdr_free ((xdrproc_t) xdr_findairport_ret,  (char *) &result);

	/*search algo and distance calculation here*/

	
	listptr = &result.findairport_ret_u.list;
	if(lat == 1.0f){
		newlist = *listptr = (airport *) malloc(sizeof(airport));
		newlist->city = (char *)malloc(strlen(cityname));
		newlist->state = (char *)malloc(strlen(statename));
		newlist->code = (char *)malloc(strlen(code));
		newlist->distance = (int) malloc(sizeof(distance));
		strcpy(newlist->city,cityname);	
		strcpy(newlist->state,statename);	
		strcpy(newlist->code,code);		
		newlist->distance = distance;		
		listptr = &newlist->next;
	}
	*listptr = NULL;
	result.airporterr = 0; 
	return &result;
}
