/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include "errno.h"
#include "place.h"
#include "airport.h"
findplace_ret *
findplace_1_svc(placename *argp, struct svc_req *rqstp)
{
	static findplace_ret result;
	float lat, longi;       
	CLIENT *clnt;
	char hostname[] = "cs1.seattleu.edu";
	char *host = hostname;
	findairport_ret  *result_1;
	airportlocation  findairport_1_arg;
	airportlist curr;
	placelist newlist;
	placelist *listptr;

	xdr_free ((xdrproc_t) xdr_findplace_ret,  (char *) &result);
	/*  city and state checks here  */

	/*  lat/long results of given city/state  */
	result.findplace_ret_u.ans.status = 0;
	lat = 1.0f;
	longi = 1.0f;

	findairport_1_arg.latitude = lat;
	findairport_1_arg.longitude = longi;
	result.findplace_ret_u.ans.latitude = lat;
	result.findplace_ret_u.ans.longitude = longi;
	#ifndef	DEBUG
		clnt = clnt_create (host, AIRPORT_DIRPROG, AIRPORT_DIR_VERS, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */

	result_1 = findairport_1(&findairport_1_arg, clnt);
	if (result_1 == (findairport_ret *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
	/*code in here for success plz*/
		curr = result_1->findairport_ret_u.list;
		listptr = &result.findplace_ret_u.ans.list;
		while(curr){
			newlist = *listptr = (place *) malloc(sizeof(place));
			newlist->city = (char *)malloc(strlen(curr->city));
			newlist->state = (char *)malloc(strlen(curr->state));
			newlist->code = (char *)malloc(strlen(curr->code));
			newlist->distance = (int)malloc(sizeof(curr->distance));
			strcpy(newlist->city,curr->city);
			strcpy(newlist->state,curr->state);
			strcpy(newlist->code,curr->code);	
			newlist->distance = curr->distance;		
			listptr = &newlist->next;
			curr = curr->next;
		}
	*listptr = NULL;
	result.placeerr = 0;
	}

	#ifndef	DEBUG
			xdr_free ((xdrproc_t) xdr_findairport_ret,  (char *) &result_1);
		clnt_destroy (clnt);
	#endif	 /* DEBUG */

	return &result;
}
