/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "place.h"
#include "errno.h"

void
places_dirprog_1(char *host, char *city, char *state)
{
	CLIENT *clnt;
	findplace_ret  *result_1;
	placename  findplace_1_arg;
	placelist curr;
	findplace_1_arg.city = city;
	findplace_1_arg.state = state;
#ifndef	DEBUG
	clnt = clnt_create (host, PLACES_DIRPROG, PLACES_DIR_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = findplace_1(&findplace_1_arg, clnt);
	if (result_1 == (findplace_ret *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		// successful result from server
		if(result_1->placeerr != 0) {
			errno = result_1->placeerr;
			perror("FAILED");
			exit(1);
		}
		// print directories
		if(result_1->findplace_ret_u.ans.status==1)
			printf("%s,%s NOT FOUND.\n",city,state);
		else if(result_1->findplace_ret_u.ans.status==2)
			printf("AMBIGUOUS CITY NAME: %s \n",city);
		printf("%s, %s: %f %f \n", city, state, result_1->findplace_ret_u.ans.latitude, result_1->findplace_ret_u.ans.longitude);
		else {
			curr = result_1->findplace_ret_u.ans.list;
			while(curr) {
				printf("code=%s, name=%s, state=%s, distance: %u \n",curr->code, curr->city, curr->state, curr->distance);
				curr = curr->next;
			}
		}
	}
#ifndef	DEBUG
	xdr_free ((xdrproc_t) xdr_findplace_ret,  (char *) &result_1);
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	places_dirprog_1 (host, argv[2],argv[3]);
exit (0);
}
